name: Terraform AWS Deploy

on:
  push:
    branches:
      - main

env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      run: terraform fmt 

    - name: Terraform Init
      run: terraform init
      
    - name: Terraform Validate
      run: terraform validate -no-color
      
    - name: Terraform Plan -var-file main.tfvars
      id: plan
      run: terraform plan -no-color -input=false

    - name: Terraform Apply -var-file main.tfvars
      run: terraform apply -input=false -no-color -auto-approve
      
